---
linters:
  enable-all: true
  disable:
    - funlen
    - gochecknoglobals
    - godox
    - golint
    - interfacer
    - lll
    - maligned
    - scopelint
    - typecheck
    - wsl
  fast: false
