sudo: false
language: go
go: 1.9.x
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: d+xjVTa22GzCk9UAG9P6g0CUHSOcxeNQZCmxamsT1Eb7m6PZXmA0bOjo0ShIndu4alth9ZwvwWZ/XI9ZfRBlnneaImCnkYr1QS6U+Jpgv+ZrVSknDDYh+JKEZ9bnR44sAyhOV8pe1ORAYY9HfZqWnz+eYHKAE8OvypnumA4eO5gmlaakk+q/H/s7lO08I+KyQIxEK2mZssiNpnWdBMS3Q7gMHzUBP5uskhBNmoimRBhVa6VcicMqFg5iQPwOh3FJjmj6frJjWp/m/4QwwvFPCrBZJJJDjn3iVXGNWnDPpaZV/ssHEXP7pWD8DQ3NVJo4HbYWxUo17BwpLklGRz/eBiNqd3MJDgjwm5o0VFRGFfl840w4Jvg4cARgClvLmnmwjkhJnyy2Xq2LQ4Bb81M0UyMWGLGdPLZxZcs2qI3k3WhQ8VArICiIliewWDdqWm1A51MUNl+OX2If74tfH+DP8PzxAqEgJD9ASMPwWm63YtIk8JgsoW7AjSlpJK6SUUuTJsr9rYaUvoEbFP/Hxr3ZijsDzhUfoLx2jGHM/K+a0GEgYlR9WfRYhVg7yQVi0lSeg7RSytv+5jCHKNSIXm5yV4XKjooT1/AgjJWaXejyybVhG+mk5dzBeJowInrsUUiu4DfNbKnfctX5ypE8Nbj4TIyCHu5Q7ETyqzk1yMYz1FU=
    on_success: change
    on_failure: always
before_install:
- go version
install:
- "./script/bootstrap"
script:
- "./script/test"
- "./script/lint"
- "./script/build all"
- ls -lh
before_deploy:
- sha256sum chronic_* > checksums.sha256
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: fNrBHm4IkORIjzkUZuY9PbBFEjYU8VLtZqEWcK0knz4wlSXTlZeNnIE5GnOybZbaVN5ts/Rif8XmXSBaPh2epCkJ00a33BsCdWs0M7UO3tg68aDA7SgWHS7nQXI5XqwmPNMHgJafO7bkVr9yBSuiuRnoiZl1n3ugPahPhG2eK7Gd2/DEWkvjpPm8SLAvqdnOD6g0Ele+BqPqMIgad3b06vPGq0cR/iOcxoFOcMP8gt0U0wSF2m7m1PGWy/GVI8LHlDqUWbErByI5KZ6vxWB3CU0x0I2BasMv9PUZIQ7Lw/cWUqf/nBArH2P93ipEcmasY5qWB8ctfrt9U/fTmK0fOBBeoKpu4wLvt7FFOqR4DcgBzHfhatNzABxZOpgAvATqAWQfx2FgF8So/Fy6/nLJYTanSQd2q9cAVxiE34M/N95zrQ1/aQE0Hovpxh8PIox613CUw9vhqCV4NQKE4clGEfm0c7MRvIbVSMntmEin3UjRDrSonjVIdJUXKziA+uwq2YKJbimqoXz5Dv7ylAFM4rKbidXHlFV5TJ2BCxpkA9Ugpjgi2j51VhuNEoKjkOt5jxlig14//3LZMR52HS81cM9S1pkqyP79dGjP4hxfONu9iLlRf+zlGe4Ookky/Tohvv85EOPhoF0FdgnbNluKKz1+dHq67j8uMvBMMvsvRkk=
  file_glob: true
  file:
  - checksums.sha256
  - chronic_*
  on:
    repo: docwhat/chronic
    tags: true
