sudo: false
language: go
go: 1.6
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
  - go version
install:
  - rake setup
script:
  - rake -j2 lint test
  - rake xbuild
  - ls -alh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Vh8S3dkW9ZsdJ3VQKNdgrelPb4AVmWW+zYMsXsN4JUPtfTsSybhkI/diacAB1Rqr5yyEB98+9sxgMvGpfH45tZkJK56wpbue52yJx+q7lU0pqtdXWgDuCO02WDZV8veM0An/3mCA1oLArAL1O6hjep1U6Q/lPivAownVznh6BzYrSeQE4C3r8DnSSYoQKeuuyqC8OaL+U6/Ya1/tGr0B9NAsO15B8x94VPAAM6/SdQwSvDbx1ZNxRU0Eyz43wcWZ/Wwyd8QU645tmI60L74lsPR42/oaZrY9ENh80GLVaMl2He7J+7JtvnNqPJ/kJ8spg2KpjvDW3Gw1NveysE3XW0Gt5Vcwflr4QbGyZVKT8dBz4h1ynBVvc0t6cwnudP0YB1oJ4fXSY16iONCtWe2ihMeL7D4rzAdKdgb9BfZB6+liNLqST+nGr200IE3hTZBRgK0bGLfGROEX2+qhLz+LJguf55Q3IwpWSf0TJs+Ivxbecz02SGed3QXcUUbTMtfjqK4wQ58RiksUmY/Nb6JEInVwJ3pBsvFH4VkmPO0wPqak/KWSyVwp/7D/Yt8+y0zWH3JbzQnAwf7AFw6N0LxwqvJtO4T6LDZo0bnG79DYZAbynDWiskQ+xcs0yaJ428jLEAyCtZ2KpEBKTnyOHvwia5pOmF3hC7J2KotC34GXfZI=
  file:
    - chronic_darwin_amd64
    - chronic_linux_386
    - chronic_linux_amd64
    - chronic_linux_ppc64le
    - chronic_windows_386.exe
    - chronic_windows_amd64.exe
  on:
    repo: docwhat/chronic
    tags: true
