sudo: false
language: go
go: 1.13.x
notifications:
  email:
    on_success: never
    on_failure: never
  pushover:
    on_success: change
    on_failure: always
    api_key:
      secure: aJRdlbBmRkm8hYb4urJHh19mBjcj5Bqb4ukdpI3EFgmujdyvxwxdBO5O9/BqfWI4CRNg3yai0uWXmqm9EprXptB9FOJswRmTFc2XXoPPFilJyWt2WOBCivj2A00pZuBepeSWna6nPcEyVHqxwLEctp+W12BxEJuZqxkTS04utNdvk8v3VCRg0wdXgxQu8PyZpWarolO9ww/bOnl7eBvWfkPO7kXzd03X0E3H7VvRGZYA8PopaalqZpCwTqk0MJw8Rug4vXB5c4PtV7UzDbIrG1aVTimxqth54QC4NEJhn45VpzBDqNYaSuqFi3s82GYaazs5lkNWwGOevfWuZ9Qmcsuhyj18+J9NU/d1/fyySeKCGx7NwUe85zDAiGWNsoJBtqD+YwZea5YiNHdFw5DY68/2Rp4UIx8ExRL1jWXhNL3jDFeVExeEr+lXb6UT2d6qHtNUImY+MffdkxCGAUIxTAOGes1/npkw3/jeTXgzi2ioceLAQ4H8K1uPZutoUkm53wnMlNMPuL8aQ9+kDSd2rATuPOP1vuAqsCdi2YUjfOb1dg2xDxYL7imMvSnV2lfL1DWVj1C2rocays1nPAWqLGF08W8/wmi8LLkFNloQjtvrV7XRLg84vIzu1Z66Ygc5wa341kcl/Ro6l0HrFWDndQYbiPhyzMUKkn6At2AGRAA=
    users:
      secure: i0VgIjERuxP6N9QG8I0rpurLJJ/Qnrlf8Xz8GWTfCL3DGAJB0pegI/I1z/YqQuk2CMqvLjYEW0BEjjgAp4st44/CfKEg6Bah5mjO2ze8XQT9PjVhONb4eg2bbsum+x62szivEHp+rrOKQMUrdS89h+p4oZY19DtlkD/i/MRdGncQgtzpBvv/2SXYAPMrxVprT47Kijn8ftIftgrvXFEshgls2Q1OqPGPeRb7lJs94podwHhhwAC6n1YyQwhtiH+9yqu0ippBeYxkmPZUJkZWdFWh8fCqKbhQlS/JWBBJVIgmNjL19OL6N52gnS3nPI/38/8W7x4cPTQnNxv4FsP5ZpDteq+WfXz9sY5yDRxwqf4KpqcEvZPEoneHfzBC+7l8l/rtpD6m3oDTq9ktiKP5LEr+MrQT9tDwJzlstnyfQ3AdL9k+AcJEpI3ezL74QAm83K3uGiaY9XFAaqWx+k+DBZt4R3EYErtesy80O2VCGnBz3HeDbftmEHh9jeneCXRiM4kvIX8EGpsOr8bfke6EGds+dC9jfqhgbm1TVhpiQOsH9nPcvkDVX6MVepQ/VhkXXohg8lnlsMoQxiXXNA8DeyRaxmfHroxS2krPMfFKNsRQGlYM1veuq9gXdB4AV/OmmC504CjrBCg7qtxQLjR8HU5HrQzK+/rUTNBKX6YKFPo=
before_install:
- go version
install:
- "./script/bootstrap"
script:
- "./script/test"
- "./script/lint"
- "./script/build all"
- ls -lh
before_deploy:
- sha256sum chronic_* > checksums.sha256
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: fNrBHm4IkORIjzkUZuY9PbBFEjYU8VLtZqEWcK0knz4wlSXTlZeNnIE5GnOybZbaVN5ts/Rif8XmXSBaPh2epCkJ00a33BsCdWs0M7UO3tg68aDA7SgWHS7nQXI5XqwmPNMHgJafO7bkVr9yBSuiuRnoiZl1n3ugPahPhG2eK7Gd2/DEWkvjpPm8SLAvqdnOD6g0Ele+BqPqMIgad3b06vPGq0cR/iOcxoFOcMP8gt0U0wSF2m7m1PGWy/GVI8LHlDqUWbErByI5KZ6vxWB3CU0x0I2BasMv9PUZIQ7Lw/cWUqf/nBArH2P93ipEcmasY5qWB8ctfrt9U/fTmK0fOBBeoKpu4wLvt7FFOqR4DcgBzHfhatNzABxZOpgAvATqAWQfx2FgF8So/Fy6/nLJYTanSQd2q9cAVxiE34M/N95zrQ1/aQE0Hovpxh8PIox613CUw9vhqCV4NQKE4clGEfm0c7MRvIbVSMntmEin3UjRDrSonjVIdJUXKziA+uwq2YKJbimqoXz5Dv7ylAFM4rKbidXHlFV5TJ2BCxpkA9Ugpjgi2j51VhuNEoKjkOt5jxlig14//3LZMR52HS81cM9S1pkqyP79dGjP4hxfONu9iLlRf+zlGe4Ookky/Tohvv85EOPhoF0FdgnbNluKKz1+dHq67j8uMvBMMvsvRkk=
  file_glob: true
  file:
  - checksums.sha256
  - chronic_*
  on:
    repo: docwhat/chronic
    tags: true
