sudo: false
language: go
go: 1.9.x
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: d+xjVTa22GzCk9UAG9P6g0CUHSOcxeNQZCmxamsT1Eb7m6PZXmA0bOjo0ShIndu4alth9ZwvwWZ/XI9ZfRBlnneaImCnkYr1QS6U+Jpgv+ZrVSknDDYh+JKEZ9bnR44sAyhOV8pe1ORAYY9HfZqWnz+eYHKAE8OvypnumA4eO5gmlaakk+q/H/s7lO08I+KyQIxEK2mZssiNpnWdBMS3Q7gMHzUBP5uskhBNmoimRBhVa6VcicMqFg5iQPwOh3FJjmj6frJjWp/m/4QwwvFPCrBZJJJDjn3iVXGNWnDPpaZV/ssHEXP7pWD8DQ3NVJo4HbYWxUo17BwpLklGRz/eBiNqd3MJDgjwm5o0VFRGFfl840w4Jvg4cARgClvLmnmwjkhJnyy2Xq2LQ4Bb81M0UyMWGLGdPLZxZcs2qI3k3WhQ8VArICiIliewWDdqWm1A51MUNl+OX2If74tfH+DP8PzxAqEgJD9ASMPwWm63YtIk8JgsoW7AjSlpJK6SUUuTJsr9rYaUvoEbFP/Hxr3ZijsDzhUfoLx2jGHM/K+a0GEgYlR9WfRYhVg7yQVi0lSeg7RSytv+5jCHKNSIXm5yV4XKjooT1/AgjJWaXejyybVhG+mk5dzBeJowInrsUUiu4DfNbKnfctX5ypE8Nbj4TIyCHu5Q7ETyqzk1yMYz1FU=
    on_success: change
    on_failure: always
before_install:
- go version
install:
- "./script/bootstrap"
script:
- "./script/test"
- "./script/lint"
- "./script/build all"
- ls -lh
before_deploy:
- sha256sum chronic_* > checksums.sha256
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Vh8S3dkW9ZsdJ3VQKNdgrelPb4AVmWW+zYMsXsN4JUPtfTsSybhkI/diacAB1Rqr5yyEB98+9sxgMvGpfH45tZkJK56wpbue52yJx+q7lU0pqtdXWgDuCO02WDZV8veM0An/3mCA1oLArAL1O6hjep1U6Q/lPivAownVznh6BzYrSeQE4C3r8DnSSYoQKeuuyqC8OaL+U6/Ya1/tGr0B9NAsO15B8x94VPAAM6/SdQwSvDbx1ZNxRU0Eyz43wcWZ/Wwyd8QU645tmI60L74lsPR42/oaZrY9ENh80GLVaMl2He7J+7JtvnNqPJ/kJ8spg2KpjvDW3Gw1NveysE3XW0Gt5Vcwflr4QbGyZVKT8dBz4h1ynBVvc0t6cwnudP0YB1oJ4fXSY16iONCtWe2ihMeL7D4rzAdKdgb9BfZB6+liNLqST+nGr200IE3hTZBRgK0bGLfGROEX2+qhLz+LJguf55Q3IwpWSf0TJs+Ivxbecz02SGed3QXcUUbTMtfjqK4wQ58RiksUmY/Nb6JEInVwJ3pBsvFH4VkmPO0wPqak/KWSyVwp/7D/Yt8+y0zWH3JbzQnAwf7AFw6N0LxwqvJtO4T6LDZo0bnG79DYZAbynDWiskQ+xcs0yaJ428jLEAyCtZ2KpEBKTnyOHvwia5pOmF3hC7J2KotC34GXfZI=
  file_glob: true
  file:
  - checksums.sha256
  - chronic_*
  on:
    repo: docwhat/chronic
    tags: true
