name: "Build Code Base ⚒️"

on: ["push", "pull_request"]

jobs:
  build:
    name: "⚒️ build"
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: detect go versios
        id: detect
        run: echo "::set-output name=go-version::$(grep "^go " go.mod | cut -d " " -f 2)"

      - name: "get go"
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.detect.outputs.go-version }}

      - name: compile
        run: |
          go run ./..
