name: release

on:
  pull_request:
  push:
  schedule:
    - cron: "53 22 * * 2"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v1
      -
        name: bootstrap
        run: |
          ./script/bootstrap
      -
        name: lint
        run: ./script/lint

  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v1
      -
        name: bootstrap
        run: |
          ./script/bootstrap
      -
        name: test
        run: |
          ./script/test

  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v1
      -
        name: bootstrap
        run: |
          ./script/bootstrap
      -
        name: goreleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: docwhat
